# Tokens 
Telegram:
  Token: "Token"
  ChatID: ChatID

Discord:
  WebHook: "DiscordWebHook"

# Database 
Database:
  Host: "localhost"
  Port: 5432
  User: "postgres"
  Password: "postgres"
  DatabaseName: "writeup"
